# Generated by Django 4.2.13 on 2026-05-14 17:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food_key",
                    models.CharField(
                        db_index=True,
                        help_text="Food-101 class name (snake_case)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "food_name",
                    models.CharField(help_text="Human-readable name", max_length=200),
                ),
                (
                    "usda_fdc_id",
                    models.CharField(
                        blank=True, help_text="USDA FoodData Central ID", max_length=50
                    ),
                ),
                (
                    "calories_kcal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "protein_g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "fat_total_g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "fat_saturated_g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "carbs_g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "sugar_g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "fiber_g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "sodium_mg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "cholesterol_mg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "vitamin_a_mcg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Vitamin A (µg RAE)",
                    ),
                ),
                (
                    "vitamin_c_mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Vitamin C (mg)",
                    ),
                ),
                (
                    "vitamin_d_mcg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Vitamin D (µg)",
                    ),
                ),
                (
                    "vitamin_b12_mcg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Vitamin B12 (µg)",
                    ),
                ),
                (
                    "calcium_mg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "iron_mg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "potassium_mg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "magnesium_mg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "zinc_mg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "glycemic_index",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Approximate GI (0–100)", null=True
                    ),
                ),
                (
                    "food_category",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Dairy", "Meat", "Grain"',
                        max_length=100,
                    ),
                ),
                (
                    "raw_usda_json",
                    models.JSONField(
                        blank=True, default=dict, help_text="Full raw USDA API response"
                    ),
                ),
                ("cached_at", models.DateTimeField(auto_now_add=True)),
                ("last_refreshed", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Food Cache Entry",
                "verbose_name_plural": "Food Cache",
                "ordering": ["food_name"],
            },
        ),
        migrations.CreateModel(
            name="FoodEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_method",
                    models.CharField(
                        choices=[
                            ("image_upload", "Image Upload"),
                            ("image_url", "Image URL"),
                            ("text_name", "Food Name (text)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Uploaded image file",
                        null=True,
                        upload_to="food_images/%Y/%m/",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, help_text="External image URL"),
                ),
                (
                    "text_input",
                    models.CharField(
                        blank=True, help_text="Food name typed by user", max_length=255
                    ),
                ),
                (
                    "predicted_food",
                    models.CharField(
                        help_text="Top-1 prediction (food_key)", max_length=100
                    ),
                ),
                (
                    "predicted_name",
                    models.CharField(
                        help_text="Human-readable predicted food name", max_length=200
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Model confidence % (0–100)",
                        max_digits=5,
                    ),
                ),
                (
                    "top3_predictions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[{food, food_key, confidence}, ...]",
                    ),
                ),
                (
                    "portion_g",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Portion size in grams",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2000),
                        ],
                    ),
                ),
                (
                    "score_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Composite personalised score (0–10)",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "score_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("moderate", "Moderate"),
                            ("poor", "Poor"),
                            ("avoid", "Avoid"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "recommended_portion_g",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="AI-recommended portion for this user (grams)",
                        null=True,
                    ),
                ),
                (
                    "score_summary",
                    models.TextField(
                        blank=True,
                        help_text="Short explanation of the score for the user",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "food_cache",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked cache entry (nutrition data source)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to="core.foodcache",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Food Entry",
                "verbose_name_plural": "Food Entries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Age in years",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                (
                    "biological_sex",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Prefer not to say"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Height in centimetres",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Weight in kilograms",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(500),
                        ],
                    ),
                ),
                (
                    "activity_level",
                    models.CharField(
                        choices=[
                            ("sedentary", "Sedentary (desk job, little exercise)"),
                            ("light", "Lightly Active (1–3 days/week)"),
                            ("moderate", "Moderately Active (3–5 days/week)"),
                            ("active", "Very Active (6–7 days/week)"),
                            ("athlete", "Athlete / Intense daily training"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                (
                    "health_goal",
                    models.CharField(
                        choices=[
                            ("lose_weight", "Lose Weight"),
                            ("maintain", "Maintain Weight"),
                            ("gain_muscle", "Gain Muscle / Bulk"),
                            ("improve_health", "Improve General Health"),
                        ],
                        default="maintain",
                        max_length=20,
                    ),
                ),
                (
                    "has_diabetes",
                    models.BooleanField(default=False, verbose_name="Diabetes"),
                ),
                (
                    "has_hypertension",
                    models.BooleanField(default=False, verbose_name="Hypertension"),
                ),
                (
                    "is_vegetarian",
                    models.BooleanField(default=False, verbose_name="Vegetarian"),
                ),
                ("is_vegan", models.BooleanField(default=False, verbose_name="Vegan")),
                (
                    "is_gluten_free",
                    models.BooleanField(
                        default=False, verbose_name="Gluten Intolerant"
                    ),
                ),
                (
                    "is_lactose_free",
                    models.BooleanField(
                        default=False, verbose_name="Lactose Intolerant"
                    ),
                ),
                (
                    "has_nut_allergy",
                    models.BooleanField(default=False, verbose_name="Nut Allergy"),
                ),
                (
                    "daily_calorie_target",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Auto-computed from Mifflin-St Jeor + activity factor",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="NutritionScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score_calories",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="How well calories fit daily target",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "score_protein",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Protein adequacy for goal",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "score_fat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Fat quality (penalises sat fat)",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "score_sugar",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Sugar penalty",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "score_sodium",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Sodium — penalised for hypertension",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "score_fiber",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Fiber bonus",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "score_vitamins",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Micronutrient richness",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "score_medical",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Medical compatibility (diabetes, allergy…)",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "warnings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='["High sodium — watch hypertension", ...]',
                    ),
                ),
                (
                    "positives",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='["Good protein source", ...]',
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_score",
                        to="core.foodentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nutrition Score",
                "verbose_name_plural": "Nutrition Scores",
            },
        ),
        migrations.AddIndex(
            model_name="foodentry",
            index=models.Index(
                fields=["user", "-created_at"], name="core_fooden_user_id_8c0e25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="foodentry",
            index=models.Index(
                fields=["predicted_food"], name="core_fooden_predict_bd0fa3_idx"
            ),
        ),
    ]
